// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS not configured.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows not configured.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux not configured.',
        );
      default:
        throw UnsupportedError(
          'Unsupported platform.',
        );
    }
  }

  // ✅ ANDROID (your existing config)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQYQ-NFApEMp4RwWy4RWeG0-BnSXsGNs',
    appId: '1:724306212346:android:eac182d19c4b87ca95a043',
    messagingSenderId: '724306212346',
    projectId: 'your-pocket-soul-coach',
    storageBucket: 'your-pocket-soul-coach.firebasestorage.app',
  );

  // ❗ iOS (YOU MUST REPLACE THESE VALUES)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbQYQ-NFApEMp4RwWy4RWeG0-BnSXsGNs',
    appId: '1:724306212346:android:eac182d19c4b87ca95a043',
    messagingSenderId: '724306212346',
    projectId: 'your-pocket-soul-coach',
    storageBucket: 'your-pocket-soul-coach.firebasestorage.app',
    iosBundleId: "com.soulpocketcoach.app.toheedapps",
  );
}