// import 'package:flutter/material.dart';
// import 'package:flutter/services.dart';
// import 'package:sizer/sizer.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:yspc/services/openai_service.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure`
// import 'package:yspc/core/env_loader.dart';
// import '../core/app_export.dart';
// import '../widgets/custom_error_widget.dart';
//
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//
//   bool _hasShownError = false;
//
//   await EnvLoader.load();
//   await OpenAIService.initialize();
//   // 🚨 CRITICAL: Custom error handling - DO NOT REMOVE
//   ErrorWidget.builder = (FlutterErrorDetails details) {
//     if (!_hasShownError) {
//       _hasShownError = true;
//       Future.delayed(const Duration(seconds: 5), () {
//         _hasShownError = false;
//       });
//       return CustomErrorWidget(errorDetails: details);
//     }
//     return const SizedBox.shrink();
//   };
//
//   // 🚨 Initialize Firebase
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//
//   // 🚨 Device orientation lock - DO NOT REMOVE
//   await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
//
//   runApp(MyApp());
// }
//
// class MyApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Sizer(builder: (context, orientation, screenType) {
//       return MaterialApp(
//         title: 'soulcoach_ai',
//         theme: AppTheme.lightTheme,
//         darkTheme: AppTheme.darkTheme,
//         themeMode: ThemeMode.light,
//         debugShowCheckedModeBanner: false,
//         routes: AppRoutes.routes,
//         initialRoute: AppRoutes.initial,
//
//         // 🚨 CRITICAL: Preserve text scale behavior
//         builder: (context, child) {
//           return MediaQuery(
//             data: MediaQuery.of(context).copyWith(
//               textScaler: const TextScaler.linear(1.0),
//             ),
//             child: child!,
//           );
//         },
//       );
//     });
//   }
// }
// <DOCUMENT filename="main.dart">
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:sizer/sizer.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import 'package:yspc/services/openai_service.dart';
import 'firebase_options.dart';
import 'package:yspc/core/env_loader.dart';
import '../core/app_export.dart';
import '../widgets/custom_error_widget.dart';

// ←←← MUST be top-level function (outside any class)
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print("Background Notification: ${message.notification?.title}");
}

// Local notifications plugin
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
FlutterLocalNotificationsPlugin();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await EnvLoader.load();
  await OpenAIService.initialize();

  // Custom error widget (keep yours)
  bool _hasShownError = false;
  ErrorWidget.builder = (FlutterErrorDetails details) {
    if (!_hasShownError) {
      _hasShownError = true;
      Future.delayed(const Duration(seconds: 5), () => _hasShownError = false);
      return CustomErrorWidget(errorDetails: details);
    }
    return const SizedBox.shrink();
  };

  // ←←← INITIALIZE FIREBASE
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // ←←← FCM: Background handler
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // ←←← Local notifications initialization (so notification shows when app is open)
  const AndroidInitializationSettings androidInit =
  AndroidInitializationSettings('@mipmap/ic_launcher');
  const DarwinInitializationSettings iosInit = DarwinInitializationSettings();
  const InitializationSettings initSettings =
  InitializationSettings(android: androidInit, iOS: iosInit);
  await flutterLocalNotificationsPlugin.initialize(initSettings);

  // ←←← FOREGROUND NOTIFICATION HANDLER (shows notification when app is open)
  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    RemoteNotification? notification = message.notification;
    if (notification != null) {
      flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification.title,
        notification.body,
        const NotificationDetails(
          android: AndroidNotificationDetails(
            'default_channel',
            'General Notifications',
            channelDescription: 'Notifications from Soul Pocket Coach',
            importance: Importance.high,
            priority: Priority.high,
          ),
        ),
      );
    }
  });

  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Sizer(
      builder: (context, orientation, screenType) {
        return MaterialApp(
          title: 'soulcoach_ai',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: ThemeMode.light,
          debugShowCheckedModeBanner: false,
          routes: AppRoutes.routes,
          initialRoute: AppRoutes.initial,
          builder: (context, child) {
            return MediaQuery(
              data: MediaQuery.of(context).copyWith(
                textScaler: const TextScaler.linear(1.0),
              ),
              child: child!,
            );
          },
        );
      },
    );
  }
}